language: ruby
rvm:
  - 2.1
  - 2.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblapack-dev
install:
  - gem install bundler
  - bundle install
  - bundle exec rake install
script: 
  - bundle exec rspec spec
